import HomeIcon from "@material-ui/icons/Home";
import WhatshotIcon from "@material-ui/icons/Whatshot";
import SubscriptionsIcon from "@material-ui/icons/Subscriptions";
import VideoLibraryIcon from "@material-ui/icons/VideoLibrary";
import HistoryIcon from "@material-ui/icons/History";
import WatchLaterIcon from "@material-ui/icons/WatchLater";
import LocalOfferIcon from "@material-ui/icons/LocalOffer";
import ThumbUpIcon from "@material-ui/icons/ThumbUp";
import VideogameAssetIcon from "@material-ui/icons/VideogameAsset";
import WifiTetheringIcon from "@material-ui/icons/WifiTethering";
import SettingsIcon from "@material-ui/icons/Settings";
import FlagIcon from "@material-ui/icons/Flag";
import HelpIcon from "@material-ui/icons/Help";
import RateReviewIcon from "@material-ui/icons/RateReview";
import AccountBoxIcon from "@material-ui/icons/AccountBox";
import MonetizationOnIcon from "@material-ui/icons/MonetizationOn";
import ExitToAppIcon from "@material-ui/icons/ExitToApp";
import PlayCircleFilledIcon from "@material-ui/icons/PlayCircleFilled";
import SecurityIcon from "@material-ui/icons/Security";
import KeyboardIcon from "@material-ui/icons/Keyboard";
import RouteItem from "../interfaces/RouteItem";

export const HOME_ROUTE: RouteItem = { title: 'Главная', to: '/', exact: true, icon: HomeIcon };
export const TRENDING_ROUTE: RouteItem = { title: 'В тренде', to: '/feed/trending', icon: WhatshotIcon };
export const SUBSCRIPTIONS_ROUTE: RouteItem = { title: 'Подписки', to: '/feed/subscriptions', icon: SubscriptionsIcon };
export const LIBRARY_ROUTE: RouteItem = { title: 'Библиотека', to: '/feed/library', icon: VideoLibraryIcon };
export const HISTORY_ROUTE: RouteItem = { title: 'История', to: '/feed/history', icon: HistoryIcon };
export const WATCH_LATER_ROUTE: RouteItem = { title: 'Смотреть позже', to: '/playlist/WL', icon: WatchLaterIcon };
export const PURCHASES_ROUTE: RouteItem = { title: 'Покупки', to: '/feed/purchases', icon: LocalOfferIcon };
export const FAVORITES_ROUTE: RouteItem = { title: 'Понравившиеся', to: '/playlist/favorites', icon: ThumbUpIcon };
export const GAMING_ROUTE: RouteItem = { title: 'Видеоигры', to: '/gaming', icon: VideogameAssetIcon };
export const STREAMING_ROUTE: RouteItem = { title: 'Трансляции', to: '/streaming', icon: WifiTetheringIcon };
export const SETTINGS_ROUTE: RouteItem = { title: 'Настройки', to: '/settings', icon: SettingsIcon };
export const REPORTS_ROUTE: RouteItem = { title: 'Жалобы', to: '/report-history', icon: FlagIcon };
export const HELP_ROUTE: RouteItem = { title: 'Справка', to: '/help', icon: HelpIcon };
export const REVIEWS_ROUTE: RouteItem = { title: 'Отправить отзыв', to: '/send-review', icon: RateReviewIcon };
export const KEYBOARD_SHORTCUTS_ROUTE: RouteItem = { title: 'Быстрые клавишы', to: '#keyoard-shortcuts', icon: KeyboardIcon };
export const ABOUT_ROUTE: RouteItem = { title: 'О сервисе', to: '/about' };
export const PRESS_ROUTE: RouteItem = { title: 'Прессе', to: '/press' };
export const COPYRIGHT_ROUTE: RouteItem = { title: 'Правообладателям', to: '/' };
export const CONTACT_US_ROUTE: RouteItem = { title: 'Связаться с нами', to: '/contact-us' };
export const CREATORS_ROUTE: RouteItem = { title: 'Авторам', to: '/creators' };
export const ADS_ROUTE: RouteItem = { title: 'Рекламодателям', to: '/ads' };
export const DEV_ROUTE: RouteItem = { title: 'Разработчикам', to: '/dev' };
export const TERMS_ROUTE: RouteItem = { title: 'Условия использования', to: '/terms' };
export const PRIVACY_ROUTE: RouteItem = { title: 'Конфиденциальность', to: '/privacy' };
export const RULES_ROUTE: RouteItem = { title: 'Правила и безопасность', to: '/policies/rules-and-safety' };
export const NEW_ROUTE: RouteItem = { title: 'Новые функции', to: '/new' };

export const CHANNEL_ROUTE: RouteItem = { title: 'Мой канал', to: '/channel/', icon: AccountBoxIcon };
export const PAID_MEMBERSHIPS_ROUTE: RouteItem = { title: 'Платные подписки', to: '/paid-memberships', icon: MonetizationOnIcon };
export const STUDIO_ROUTE: RouteItem = { title: 'Творческая студия YouTube', to: '/studio', icon: PlayCircleFilledIcon };
export const PERSONAL_DATA_ROUTE: RouteItem = { title: 'Личные данные на YouTube', to: '/personal-data', icon: SecurityIcon };
export const SIGN_OUT_ROUTE: RouteItem = { title: 'Выйти', to: '/sign-out', icon: ExitToAppIcon };
